# Generated by Django 2.1 on 2018-08-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='title',
            field=models.CharField(default='db config', max_length=64, verbose_name='title'),
        ),
    ]
