# Generated by Django 2.1 on 2018-08-27 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(default='', max_length=300, verbose_name='host')),
            ],
        ),
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='endpoint')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoint.BaseUrl')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
