# Generated by Django 2.1 on 2018-08-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0002_endpoint_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='host',
            new_name='hostname',
        ),
    ]
